# Generated by Django 3.2.7 on 2021-10-07 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='grupoanulado',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'No Activo')], default='1', help_text='Seleccione el estado', max_length=1),
        ),
    ]
