# Generated by Django 3.2.7 on 2021-10-07 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_alter_grupo_grupoanulado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='clienteanulador',
        ),
        migrations.AddField(
            model_name='cliente',
            name='clienteanulado',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'No Activo')], default='1', help_text='Seleccione el estado', max_length=1),
        ),
        migrations.AlterField(
            model_name='producto',
            name='productoanulado',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'No Activo')], default='1', help_text='Seleccione el estado', max_length=1),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='proveedoranulado',
            field=models.CharField(choices=[('1', 'Activo'), ('0', 'No Activo')], default='1', help_text='Seleccione el estado', max_length=1),
        ),
    ]
